// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using websiteSPcongnghe.Data;

#nullable disable

namespace websiteSPcongnghe.Migrations
{
    [DbContext(typeof(websiteSPcongngheContext))]
    partial class websiteSPcongngheContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("websiteSPcongnghe.Models.Danhmuc", b =>
                {
                    b.Property<int>("DanhmucID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DanhmucID"), 1L, 1);

                    b.Property<string>("Tendanhmuc")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DanhmucID");

                    b.ToTable("Danhmuc");
                });

            modelBuilder.Entity("websiteSPcongnghe.Models.Quyenhan", b =>
                {
                    b.Property<int>("QuyenhanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuyenhanID"), 1L, 1);

                    b.Property<string>("Quyen")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("QuyenhanID");

                    b.ToTable("Quyenhan");
                });

            modelBuilder.Entity("websiteSPcongnghe.Models.Thuonghieu", b =>
                {
                    b.Property<int>("ThuonghieuID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ThuonghieuID"), 1L, 1);

                    b.Property<string>("Tenthuonghieu")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ThuonghieuID");

                    b.ToTable("Thuonghieu");
                });
#pragma warning restore 612, 618
        }
    }
}
